
import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQuery } from "./baseQuery";

export const baseApi = createApi({
    reducerPath: "api",
    baseQuery: baseQuery,
    tagTypes: [
        "User",
        "Category",
        "Course",
        "Curriculum",
        "Media",
        "Notes",
        "Audio",
        "Video",
        "Images",
        "Test",
        "Archive",
        "Questions",
        "Results",
        "Set",
        "OMR",
        "TestEnrollment",
        "BundleEnrollment",
        "Live_Class",
        "Notifications",
        "Transaction",
        "Activity",
        "LinkedDevice",
        "Profile",
        "Banner",
        "Page",
        "Welcome",
        "Splash",
        "Onboarding",
        "Role",
        "Permission",
        "Subscription",
        "Position",
        "Pages",
        "Gorkhapatra",
        "Analytics",
        "Ticket",
        "TicketReply",
        "TicketType",
        "Discussion",
        "Moderation",
        "Comment",
        "ResetRequest",
        "Controls",
        "Theme",
        "MenuCounts",
        "SmtpSetting",
        "CourseSetting",
        "LoginType",
        "EmailTemplate",
        "ApiSetting",
        "ZoomAccount",
        "QuestionLabel",
        "Referral",
        "PointsConfig",
        "PointsTransaction",
        "ReferralOverview",
        "MarketingLink",
        "CouponCode",
        "NotificationStats",
        "NotificationEvents",
        "TestCategory"
    ],
    endpoints: () => ({}),
});
